MAX_LENGTH_FIELDS_OF_RECIPES = 200

MAX_LENGTH_FIELD_OF_COLOR = 7

MIN_VALIDATION_VALUE = 1

MAX_VALIDATION_VALUE_OF_COOKING_TIME = 1440

MAX_VALIDATION_VALUE_OF_AMOUNT = 5000

MAX_LENGTH_FIELDS_OF_USERS = 150

MAX_LENGTH_FIELD_OF_EMAIL = 254
